sudo: true
language: cpp

compiler:
  - gcc

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - pip install codecov
  - sudo apt-get update -qq

#install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script: 
 - $CXX --version
 - g++ --version
 - qmake
 - cat Makefile
 - make

after_success:
  - codecov